/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.SinhVienDangKiThongKeDAO;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.MonHocThongKe;
import model.SinhVienDangKiThongKe;

/**
 *
 * @author Admin
 */
public class BangDiemMonHocFrm extends javax.swing.JFrame {
    DefaultTableModel bangDiemModel;
    List<SinhVienDangKiThongKe> thongKeSinhVien;
    /**
     * Creates new form BangDiemMonHocFrm
     */
    public BangDiemMonHocFrm(MonHocThongKe mon) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tenMonHocJLabel.setText("Môn học: "+mon.getTenMon());
        bangDiemModel = new DefaultTableModel();
        bangDiemModel = (DefaultTableModel) bangDiemJTable.getModel();        
        thongKeSinhVien = new SinhVienDangKiThongKeDAO().layDSSVDKTK(mon);
        DecimalFormat f = new DecimalFormat("#0.00");
        int i = 1;
        for (SinhVienDangKiThongKe sinhVienDangKiThongKe : thongKeSinhVien) {
            bangDiemModel.addRow(new Object[]{
            i,sinhVienDangKiThongKe.getSinhVien().getID(), sinhVienDangKiThongKe.getSinhVien().getTenDayDu(),
            f.format(sinhVienDangKiThongKe.getDiemTP1()),f.format(sinhVienDangKiThongKe.getDiemTP2()),
            f.format(sinhVienDangKiThongKe.getDiemTP3()),f.format(sinhVienDangKiThongKe.getDiemThi()),
            f.format(sinhVienDangKiThongKe.getDiemTB())
            });
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tieuDeJLabel = new javax.swing.JLabel();
        tenMonHocJLabel = new javax.swing.JLabel();
        thoatButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDiemJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tieuDeJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tieuDeJLabel.setText("Bảng điểm chi tiết");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(tieuDeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tieuDeJLabel))
        );

        tenMonHocJLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tenMonHocJLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenMonHocJLabel.setText("{mon hoc}");

        thoatButton.setText("Thoát");
        thoatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tenMonHocJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(thoatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenMonHocJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoatButton)
                .addGap(23, 23, 23))
        );

        bangDiemJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sinh viên", "Tên sinh viên", "Điểm TP1", "Điểm TP2", "Điểm TP3", "Điểm thi", "Điểm TB"
            }
        ));
        jScrollPane1.setViewportView(bangDiemJTable);
        if (bangDiemJTable.getColumnModel().getColumnCount() > 0) {
            bangDiemJTable.getColumnModel().getColumn(0).setMinWidth(40);
            bangDiemJTable.getColumnModel().getColumn(0).setMaxWidth(40);
            bangDiemJTable.getColumnModel().getColumn(1).setMinWidth(120);
            bangDiemJTable.getColumnModel().getColumn(1).setMaxWidth(120);
            bangDiemJTable.getColumnModel().getColumn(3).setMinWidth(80);
            bangDiemJTable.getColumnModel().getColumn(3).setMaxWidth(80);
            bangDiemJTable.getColumnModel().getColumn(4).setMinWidth(80);
            bangDiemJTable.getColumnModel().getColumn(4).setMaxWidth(80);
            bangDiemJTable.getColumnModel().getColumn(5).setMinWidth(80);
            bangDiemJTable.getColumnModel().getColumn(5).setMaxWidth(80);
            bangDiemJTable.getColumnModel().getColumn(6).setMinWidth(80);
            bangDiemJTable.getColumnModel().getColumn(6).setMaxWidth(80);
            bangDiemJTable.getColumnModel().getColumn(7).setMinWidth(80);
            bangDiemJTable.getColumnModel().getColumn(7).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_thoatButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDiemJTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tenMonHocJLabel;
    private javax.swing.JButton thoatButton;
    private javax.swing.JLabel tieuDeJLabel;
    // End of variables declaration//GEN-END:variables
}
