/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SinhVienDangKiThongKeDAO;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.HocKy;
import model.SinhVienDangKiThongKe;
import model.SinhVienThongKe;

/**
 *
 s* @author Admin
 */
public class BangDiemChiTietSinhVienFrm extends javax.swing.JFrame {
    DefaultTableModel bangDiemSVTableModel;
    SinhVienThongKe svtk;
    HocKy hk;
    List<SinhVienDangKiThongKe> bangDiemSV;
    /**
     * Creates new form BangDiemChiTietSinhVienFrm
     */
    public BangDiemChiTietSinhVienFrm(SinhVienThongKe sv, HocKy hk) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.svtk = sv;
        this.hk = hk;
        bangDiemSVTableModel = (DefaultTableModel) bangDiemSVJTable.getModel();
        hocKyJLabel.setText(hk.getTenHocKy());
        maSVJLabel.setText("Sinh viên: "+svtk.getID()+" - "+svtk.getTenDayDu());
        bangDiemSV = new SinhVienDangKiThongKeDAO().layDSSVDKTK(svtk, hk);
        DecimalFormat f = new DecimalFormat("#0.00");
        bangDiemSVTableModel.setRowCount(0);
        int i=1;
        for (SinhVienDangKiThongKe svdktk : bangDiemSV) {
            bangDiemSVTableModel.addRow(new Object[]{
            i, svdktk.getTenMH(),svdktk.getSoTC(),f.format(svdktk.getDiemTP1()),
                f.format(svdktk.getDiemTP2()),f.format(svdktk.getDiemTP3()),f.format(svdktk.getDiemThi()),
                f.format(svdktk.getDiemTB())
            });
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeJLabel = new javax.swing.JLabel();
        hocKyJLabel = new javax.swing.JLabel();
        maSVJLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        thoatJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDiemSVJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 240, 240));

        tieuDeJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tieuDeJLabel.setText("Bảng điểm chi tiết");

        hocKyJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hocKyJLabel.setText("Học kì: {}");

        maSVJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maSVJLabel.setText("Sinh viên: {}");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(tieuDeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(hocKyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(maSVJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tieuDeJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hocKyJLabel)
                    .addComponent(maSVJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(120, 240, 240));

        thoatJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thoatJButton.setText("Thoát");
        thoatJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(thoatJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(thoatJButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        bangDiemSVJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên môn học", "Số TC", "Điểm TP1", "Điểm TP2", "Điểm TP3", "Điểm thi", "Điểm TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bangDiemSVJTable);
        if (bangDiemSVJTable.getColumnModel().getColumnCount() > 0) {
            bangDiemSVJTable.getColumnModel().getColumn(0).setMinWidth(40);
            bangDiemSVJTable.getColumnModel().getColumn(0).setMaxWidth(40);
            bangDiemSVJTable.getColumnModel().getColumn(2).setMinWidth(80);
            bangDiemSVJTable.getColumnModel().getColumn(2).setMaxWidth(80);
            bangDiemSVJTable.getColumnModel().getColumn(3).setMinWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(3).setMaxWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(4).setMinWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(4).setMaxWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(5).setMinWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(5).setMaxWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(6).setMinWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(6).setMaxWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(7).setMinWidth(100);
            bangDiemSVJTable.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoatJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatJButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_thoatJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDiemSVJTable;
    private javax.swing.JLabel hocKyJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maSVJLabel;
    private javax.swing.JButton thoatJButton;
    private javax.swing.JLabel tieuDeJLabel;
    // End of variables declaration//GEN-END:variables
}
