/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.SinhVien;

/**
 *
 * @author Admin
 */
public class GiaoDiemSinhVienFrm extends javax.swing.JFrame {
    SinhVien sv;
    /**
     * Creates new form GiaoDiemSinhVienFrm
     */
    public GiaoDiemSinhVienFrm(SinhVien sv) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.sv = sv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeJLabel = new javax.swing.JLabel();
        xemTKBJButton = new javax.swing.JButton();
        dangKiHocJButton = new javax.swing.JButton();
        dangXuatJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 120, 240));

        tieuDeJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tieuDeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        tieuDeJLabel.setText("Giao diện sinh viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(tieuDeJLabel)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tieuDeJLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        xemTKBJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xemTKBJButton.setText("Xem thời khóa biểu");
        xemTKBJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemTKBJButtonActionPerformed(evt);
            }
        });

        dangKiHocJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dangKiHocJButton.setText("Đăng kí học");
        dangKiHocJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangKiHocJButtonActionPerformed(evt);
            }
        });

        dangXuatJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dangXuatJButton.setText("Đăng xuất");
        dangXuatJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xemTKBJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dangKiHocJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dangXuatJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(xemTKBJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dangKiHocJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dangXuatJButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dangKiHocJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangKiHocJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dangKiHocJButtonActionPerformed

    private void xemTKBJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemTKBJButtonActionPerformed
        this.setVisible(false);
        new XemTKBFrm(sv).setVisible(true);
    }//GEN-LAST:event_xemTKBJButtonActionPerformed

    private void dangXuatJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatJButtonActionPerformed
        this.setVisible(false);
        new DangNhapFrm().setVisible(true);
    }//GEN-LAST:event_dangXuatJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangKiHocJButton;
    private javax.swing.JButton dangXuatJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tieuDeJLabel;
    private javax.swing.JButton xemTKBJButton;
    // End of variables declaration//GEN-END:variables
}
