/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MonHocThongKeDAO;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonHocThongKe;

/**
 *
 * @author Admin
 */
public class MonHocThongKeFrm extends javax.swing.JFrame {
    DefaultTableModel monHocThongKeModel;
    List<MonHocThongKe> listMHTK;
    /**
     * Creates new form ThongKeMonHocFrm
     */
    public MonHocThongKeFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        monHocThongKeModel = new DefaultTableModel();
        monHocThongKeModel = (DefaultTableModel) bangTKMonHocJTable.getModel();
        listMHTK = new MonHocThongKeDAO().layDSMHTK();
        DecimalFormat f = new DecimalFormat("#0.00");
        int i=1;
        for (MonHocThongKe monHocThongKe : listMHTK) {
            String diemTB ="";
            String tiLeQua = "";
            if(monHocThongKe.getDiemTB()!=-1.0)
                diemTB = f.format(monHocThongKe.getDiemTB());
            if(monHocThongKe.getTiLeQuaMon()!=-1.0)
                tiLeQua = f.format(monHocThongKe.getTiLeQuaMon())+"%";
            monHocThongKeModel.addRow(new Object[]{
            
            i, monHocThongKe.getID(), monHocThongKe.getTenMon(),monHocThongKe.
                    getSoTinChi(),diemTB,tiLeQua
            });
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tieuDeJLabel = new javax.swing.JLabel();
        thoatJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangTKMonHocJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tieuDeJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tieuDeJLabel.setText("Thống kê môn học theo tỉ lệ sinh viên qua");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tieuDeJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(tieuDeJLabel))
        );

        thoatJButton.setBackground(new java.awt.Color(255, 255, 255));
        thoatJButton.setText("Thoát");
        thoatJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thoatJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoatJButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        bangTKMonHocJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã MH", "Tên MH", "Số TC", "Điểm TB", "Tỉ lệ SV qua môn"
            }
        ));
        bangTKMonHocJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangTKMonHocJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangTKMonHocJTable);
        if (bangTKMonHocJTable.getColumnModel().getColumnCount() > 0) {
            bangTKMonHocJTable.getColumnModel().getColumn(0).setMinWidth(40);
            bangTKMonHocJTable.getColumnModel().getColumn(0).setMaxWidth(40);
            bangTKMonHocJTable.getColumnModel().getColumn(1).setMinWidth(90);
            bangTKMonHocJTable.getColumnModel().getColumn(1).setMaxWidth(90);
            bangTKMonHocJTable.getColumnModel().getColumn(3).setMinWidth(80);
            bangTKMonHocJTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangTKMonHocJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangTKMonHocJTableMouseClicked
        try {
            MonHocThongKe mon = listMHTK.get(bangTKMonHocJTable.getSelectedRow());
            if(mon.getDiemTB()==-1.0||mon.getTiLeQuaMon()==-1.0)
                throw new Exception("Thông tin môn học trống");
                        else
                new BangDiemMonHocFrm(mon).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_bangTKMonHocJTableMouseClicked

    private void thoatJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatJButtonActionPerformed
        this.setVisible(false);
        new ThongKeFrm().setVisible(true);
    }//GEN-LAST:event_thoatJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangTKMonHocJTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton thoatJButton;
    private javax.swing.JLabel tieuDeJLabel;
    // End of variables declaration//GEN-END:variables
}
