/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HocKyDAO;
import controller.SinhVienThongKeDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.HocKy;
import model.SinhVienThongKe;

/**
 *
 * @author Admin
 */
public class SinhVienGioiThongKeFrm extends javax.swing.JFrame {
    private DefaultTableModel bangThongKeSinhVienTableModel;
    List<HocKy> dsHocKy;
    List<SinhVienThongKe> dsSVTK;
    /**
     * Creates new form SinhVienGioThongKeFrm
     */
    public SinhVienGioiThongKeFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dsHocKy = new HocKyDAO().layDSHocKy();
        dsSVTK = new ArrayList<>();
        bangThongKeSinhVienTableModel = (DefaultTableModel) bangThongKeSinhVienJTable.getModel();
        for(HocKy hk : dsHocKy){
            chonHocKiJComboBox.addItem(hk.getTenHocKy());
        }
        chonHocKiJComboBox.setSelectedIndex(0);
        hienThiDSSVTK();
    }
    private void hienThiDSSVTK(){
        HocKy hk = dsHocKy.get(chonHocKiJComboBox.getSelectedIndex());
        dsSVTK = new SinhVienThongKeDAO().layDSKeyQuaSV(hk);
        bangThongKeSinhVienTableModel.setRowCount(0);
        DecimalFormat f = new DecimalFormat("#0.00");
        int thutu = 1;
        for(SinhVienThongKe svtk : dsSVTK){
            bangThongKeSinhVienTableModel.addRow(new Object[]{
                thutu, svtk.getID(), svtk.getTenDayDu(), svtk.getKhoa(),hk.getTenHocKy(),svtk.getSoTCHocKy(), f.format(svtk.getDiemTBHocKy())
            });
            thutu++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeJLabel = new javax.swing.JLabel();
        chonHocKiJLabel = new javax.swing.JLabel();
        chonHocKiJComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        thoatJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangThongKeSinhVienJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 240, 240));

        tieuDeJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tieuDeJLabel.setText("Thống kê sinh viên giỏi");

        chonHocKiJLabel.setText("Chọn học kì");

        chonHocKiJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonHocKiJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(tieuDeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chonHocKiJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chonHocKiJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieuDeJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chonHocKiJLabel)
                    .addComponent(chonHocKiJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(120, 240, 240));

        thoatJButton.setText("Thoát");
        thoatJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(thoatJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoatJButton)
                .addContainerGap())
        );

        bangThongKeSinhVienJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "XH", "Mã SV", "Tên SV", "Khóa", "Học kì", "Số TC trong học kì", "ĐTB học kì"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bangThongKeSinhVienJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangThongKeSinhVienJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangThongKeSinhVienJTable);
        if (bangThongKeSinhVienJTable.getColumnModel().getColumnCount() > 0) {
            bangThongKeSinhVienJTable.getColumnModel().getColumn(0).setMinWidth(60);
            bangThongKeSinhVienJTable.getColumnModel().getColumn(0).setMaxWidth(60);
            bangThongKeSinhVienJTable.getColumnModel().getColumn(1).setMinWidth(80);
            bangThongKeSinhVienJTable.getColumnModel().getColumn(1).setMaxWidth(80);
            bangThongKeSinhVienJTable.getColumnModel().getColumn(3).setMinWidth(60);
            bangThongKeSinhVienJTable.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonHocKiJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonHocKiJComboBoxActionPerformed
        hienThiDSSVTK();
    }//GEN-LAST:event_chonHocKiJComboBoxActionPerformed

    private void thoatJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatJButtonActionPerformed
        this.setVisible(false);
        new ThongKeFrm().setVisible(true);
    }//GEN-LAST:event_thoatJButtonActionPerformed

    private void bangThongKeSinhVienJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangThongKeSinhVienJTableMouseClicked
        new BangDiemChiTietSinhVienFrm(dsSVTK.get(bangThongKeSinhVienJTable.getSelectedRow()),
                dsHocKy.get(chonHocKiJComboBox.getSelectedIndex())).setVisible(true);
    }//GEN-LAST:event_bangThongKeSinhVienJTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangThongKeSinhVienJTable;
    private javax.swing.JComboBox<String> chonHocKiJComboBox;
    private javax.swing.JLabel chonHocKiJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton thoatJButton;
    private javax.swing.JLabel tieuDeJLabel;
    // End of variables declaration//GEN-END:variables
}
